title: Maria Soto
description: Modeling of Water Consumption for Small Rural Communities via Decision Tree Regressor vs Random Forrest Regressor [AOS C111/204 project site]
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-modernist
